name: Build Python Distribution

on: push

jobs:
  build_release:
    # if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: jurplel/install-qt-action@v3
      with:
        python-version: "3.12"
    - run: python3 virtualenv venv
    - run: .\venv\bin\activate.ps
    - run: pip install .
    - run: cmake .
    - run: cmake --build .
    - run: Compress-Archive -Path * -Destination OSCR.zip
    - uses: actions/upload-artifact@v2
      with:
        name: build_release
        path: OSCR.zip

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ build_release ]
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: build_release
          path: dist
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/OSCR.zip
